apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-router-config
  labels:
    {{- include "operator.labels" . | nindent 4 }}

data:
  configuration.yaml: |
    supergraph:
      listen: 0.0.0.0:80
    health_check:
      listen: 0.0.0.0:8088
    telemetry:
      experimental_logging:
        format: json 
      metrics:
        common:
          service_namespace: "default"
          service_name: router
          buckets:
            - 0.1
        prometheus:
          enabled: true
          path: /metrics
        otlp:
          enabled: true
